version: '3'

services:
        web:
                image: 'captacion-php'
                ports:
                        - '8000:8000'
                volumes:
                        - ./:/app
                command: php artisan serve --host=0.0.0.0

        mysql:
                image: 'mysql:5.7'
                ports:
                        - '3306:3306'
                environment:
                        - MYSQL_ROOT_PASSWORD=toor
                volumes:
                        - mysql-data:/var/lib/mysql
        phpmyadmin:
                image: 'phpmyadmin/phpmyadmin'
                ports:
                        - '8080:80'
                environment:
                        - PMA_ARBITRARY=0
                        - PMA_HOST=127.0.0.1
                        - PMA_VERBOSE=Mysql localhost
                        - PMA_PORT=3306
volumes:
        mysql-data:
