version: '3'

services:
        web:
                image: 'captacion-php'
                ports:
                        - '8000:8000'
                volumes:
                        - ./:/app
                command: php artisan serve --host=0.0.0.0
                links:
                        - 'mysql'
                        - 'mailtrap'
        mysql:
                image: 'mysql:5.7'
                ports:
                        - '3306:3306'
                environment:
                        - MYSQL_ROOT_PASSWORD=toor
                volumes:
                        - mysql-data:/var/lib/mysql
        phpmyadmin:
                image: 'phpmyadmin/phpmyadmin'
                ports:
                        - '8080:80'
                        - '8443:443'
                          #depends_on:
                links:
                        - 'mysql'
                environment:
                        - PMA_ARBITRARY=0
                        - PMA_VERBOSE=Mysql localhost
                        - PMA_HOST=mysql
                        - PMA_PORT=3306

        mailtrap:
                image: 'eaudeweb/mailtrap'
                ports:
                        - '8090:80'
volumes:
        mysql-data:
